In [4]:
# 稳定双共轭梯度法
import numpy as np
n = 100
converged = np.array([False])
v=np.zeros((n,1))
r=np.zeros((n,1))
r0_hat=np.zeros((n,1))
p=np.zeros((n,1))
s=np.zeros((n,1))
t=np.zeros((n,1))
A = np.random.rand(n, n)
b = np.random.rand(n, 1)
x = np.ones((n, 1))
tol = 1e-6
limit = 1e6
print('系数矩阵 A:\n', A)
print('右边向量 b:\n', b)
print('初始猜测值 x0:\n', x)
r[:] = b[:]-np.dot(A, x)
r0_hat[:] = r[:]
rho0 = alpha = w = v[:] = p[:] = 1.0
rho1 = np.dot(np.transpose(r0_hat), r)
iters = 0
while(True):
    iters = iters+1
    converged[:] = (np.linalg.norm(r) < tol*np.linalg.norm(b))
    if converged == True or iters == limit:
        break
    # if iters < 5:
    #     print("先验值x({}):\n{}".format(iters, x))
    beta = (rho1/rho0)*(alpha/w)
    p[:, 0] = r[:, 0]+beta*(p[:, 0]-w*v[:, 0])
    v[:] = np.dot(A, p)
    alpha = rho1/np.dot(np.transpose(r0_hat), v)
    s[:, 0] = r[:, 0]-alpha*v[:, 0]
    t[:] = np.dot(A, s)
    w = np.dot(np.transpose(t), s)/np.dot(np.transpose(t), t)
    rho0 = rho1
    rho1 = -w*np.dot(np.transpose(r0_hat), t)
    x[:, 0] = x[:, 0]+alpha*p[:, 0]+w*s[:, 0]
    r[:, 0] = s[:, 0]-w*t[:, 0]

print('迭代次数 iters:\n', iters)
print('解向量 x:\n', x)


系数矩阵 A:
 [[0.56606245 0.94474382 0.88643053 ... 0.60941764 0.36003055 0.06674526]
 [0.12495507 0.62850795 0.24595021 ... 0.82875466 0.56121335 0.84449172]
 [0.90029556 0.10601449 0.71154883 ... 0.38198694 0.17814103 0.61822735]
 ...
 [0.92317702 0.79329147 0.38278866 ... 0.66321832 0.76492666 0.16668901]
 [0.16121429 0.53631929 0.44901258 ... 0.81249359 0.04968624 0.37257374]
 [0.28878459 0.99219487 0.59463926 ... 0.43418736 0.97592198 0.75136425]]
右边向量 b:
 [[0.13823889]
 [0.42009063]
 [0.19880851]
 [0.75813491]
 [0.89155039]
 [0.2002973 ]
 [0.82045987]
 [0.41130177]
 [0.90825352]
 [0.70784809]
 [0.14191574]
 [0.7748617 ]
 [0.59028822]
 [0.5583594 ]
 [0.15734547]
 [0.970589  ]
 [0.79446861]
 [0.6016322 ]
 [0.46802876]
 [0.81397737]
 [0.04475054]
 [0.40739779]
 [0.74007401]
 [0.3651808 ]
 [0.18636738]
 [0.12828891]
 [0.63837561]
 [0.8165334 ]
 [0.62432254]
 [0.53035756]
 [0.36754097]
 [0.23876787]
 [0.13254886]
 [0.46729024]
 [0.64428269]
 [0.19234527]
 [0.43513232]
 [0.0031923 ]
 [0.98

/tmp/ipykernel_91755/778330389.py:34: RuntimeWarning: divide by zero encountered in true_divide
  alpha = rho1/np.dot(np.transpose(r0_hat), v)


KeyboardInterrupt: 

In [5]:
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import bicgstab
import numpy as np
n=100
A = np.random.rand(n, n)
b = np.random.rand(n, 1)
print('系数矩阵 A:\n', A)
print('右边向量 b:\n', b)

A = csc_matrix(A)
x, exit_code = bicgstab(A, b)
print('解向量 x:\n', x)

系数矩阵 A:
 [[0.3897723  0.45803012 0.43535179 ... 0.85700028 0.1040463  0.75208542]
 [0.76889477 0.60692756 0.16403    ... 0.46808345 0.41823221 0.63974318]
 [0.9103373  0.05629488 0.14711041 ... 0.2284641  0.63985024 0.02398402]
 ...
 [0.52647804 0.6165487  0.78691725 ... 0.85008234 0.14062445 0.25391739]
 [0.21126151 0.7588301  0.70636732 ... 0.86965106 0.27897302 0.58635377]
 [0.16516701 0.53247118 0.394164   ... 0.16581187 0.52298513 0.94611828]]
右边向量 b:
 [[0.66988664]
 [0.92280818]
 [0.60638526]
 [0.18544486]
 [0.94822587]
 [0.93092108]
 [0.06964112]
 [0.70416473]
 [0.08593659]
 [0.00847159]
 [0.05009779]
 [0.3501117 ]
 [0.57247868]
 [0.03725542]
 [0.83236985]
 [0.69570358]
 [0.56600364]
 [0.57758818]
 [0.25992882]
 [0.91788743]
 [0.85949558]
 [0.95607712]
 [0.70041569]
 [0.9547412 ]
 [0.12438088]
 [0.73859229]
 [0.86533677]
 [0.87723689]
 [0.60904151]
 [0.40399905]
 [0.70454663]
 [0.04004413]
 [0.73458861]
 [0.31573331]
 [0.01463222]
 [0.7341364 ]
 [0.18868883]
 [0.60889965]
 [0.06